### ISSUE TITLE
Deprecated plasma/core

### ISSUE THREAD

**Issue by GothShoot** [WyriHaximus/reactphp-simple-orm#30]
Hello,

I have forked your project because I'm interested by it.
But when I try to install the dependency, plasma/core and charlottedunois/set have issues.
After a search on packagist, plasma/core is abandoned and charlottedunois/set is not found ...

Any project to fix this and continue project ?

Cordially

GothShoot

**Comment by WyriHaximus** [comment]
Hey @GothShoot yes, been busy with some other things but the plan is to start working again on this project soon. Noticed the deleted package as well today

**Comment by bartvanhoutte** [comment]
@WyriHaximus I've been working on a project that used `plasma/core` and have switched it out for `drift/dbal` with success. Hope this comment might save you some time.

**Comment by WyriHaximus** [comment]
@bartvanhoutte thanks, essentally only need to replace the query builder now so that shouldn't be to hard :)

**Comment by GothShoot** [comment]
I try the solution soon, and I try usage on PHP 7.4 for usage on my project :)

**Comment by GothShoot** [comment]
@WyriHaximus I have studied the solution provided by Bartvanhoutte and I see a lot of things change with implementing Doctrine QuerryBuilder used by drift/dbal and it needs lots of updates in your project for work fine.
I can propose a Pull Request for fix it but I'm not sure it works like you want 🤔

**Comment by WyriHaximus** [comment]
@GothShoot no need to, already half way swapping out the query builder with another one locally. Will have a PR up today

**Comment by WyriHaximus** [comment]
But thank you for looking into it 👍

**Comment by WyriHaximus** [comment]
PR is up at #31 and in retrospect #29 was a hint

**Comment by WyriHaximus** [comment]
One more issue to to tackle and then this is resolved.

**Comment by GothShoot** [comment]
Thank's

**Comment by WyriHaximus** [comment]
@GothShoot @bartvanhoutte Just merged the PR (#31) that swaps out the query builder with @shadowhand's beware that it includes some breaking changes (where and order arguments) and a bump to PHP 7.4
